import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { NotionRenderer } from "react-notion-x";
import { Code } from "react-notion-x/build/third-party/code";

// utils
import { getPage } from "utils/notino";

export const getStaticPaths = async () => {
  const {
    data: { results },
  } = await axios.post(`/databases/${process.env.NEXT_PUBLIC_DATABASE}/query`, {
    filter: {
      or: [],
    },
  });

  return {
    paths: results.map((item) => ({ params: { id: item.id } })),
    fallback: true,
  };
};

export const getStaticProps = async (context) => {
  const page = await getPage(context.params.id);

  return {
    props: {
      page,
    },
  };
};

const Index = ({ page }) => {
  return (
    <>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <NotionRenderer
          recordMap={page}
          components={{ Code, nextImage: Image }}
        />
      </div>
    </>
  );
};

export default Index;
