import Head from "next/head";
import Link from "next/link";
import axios from "axios";

export const getStaticProps = async () => {
  const {
    data: { results },
  } = await axios.post(`/databases/${process.env.NEXT_PUBLIC_DATABASE}/query`, {
    filter: {
      or: [],
    },
  });

  return {
    props: {
      data: results,
    },
  };
};

interface Props {
  data: any[];
}

const Index = ({ data = [] }: Props) => {
  return (
    <>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data.map((item) => {
          return (
            <Link key={item.id} href={`/posts/${item.id}`}>
              {item.properties["이름"].title[0].plain_text}
            </Link>
          );
        })}
      </div>
    </>
  );
};

export default Index;
