import Head from "next/head";
import axios from "axios";
import { NotionRenderer } from "react-notion-x";
import { Code } from "react-notion-x/build/third-party/code";

// utils
import { getPage } from "utils/notino";

export const getStaticProps = async () => {
  const page = await getPage("a11738b42cf74e24a76a0d7de0b94b6f");

  return {
    props: {
      page,
    },
  };
};

const Index = ({ page }) => {
  return (
    <>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <NotionRenderer recordMap={page} components={{ Code }} />
      </div>
    </>
  );
};

export default Index;
